// Package importer parses a generated script back into its parameters.
//
// There is one entry point for both sources of script text — a file the user
// uploads and a file read from the library — so anything borggen produced
// round-trips exactly, regardless of where it came from.
package importer

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"borggen/internal/generator"
	"borggen/internal/model"
)

// ErrNoMarker means the text carries no borggen metadata. Heuristic parsing of
// foreign scripts is deliberately not implemented: guessing would produce a
// job that looks right and backs up the wrong thing.
var ErrNoMarker = errors.New("no borggen:meta block in the script — this file was not generated by borggen")

// Result is what a successful parse yields.
type Result struct {
	Job      model.BackupJob `json:"job"`
	UserPre  string          `json:"user_pre"`
	UserPost string          `json:"user_post"`
	Warnings []model.Problem `json:"warnings"`
}

// Parse extracts parameters and hand-written zones from a script.
func Parse(script string) (Result, error) {
	var res Result

	raw, err := metaJSON(script)
	if err != nil {
		return res, err
	}
	if err := json.Unmarshal([]byte(raw), &res.Job); err != nil {
		return res, fmt.Errorf("parse meta block: %w", err)
	}

	res.Job.Normalize()
	res.Warnings = res.Job.Validate()
	res.UserPre, res.UserPost = generator.ExtractUserZones(script)
	return res, nil
}

// metaJSON pulls the commented JSON out of the marker block.
func metaJSON(script string) (string, error) {
	lines := strings.Split(strings.ReplaceAll(script, "\r\n", "\n"), "\n")

	start, end := -1, -1
	for i, l := range lines {
		switch strings.TrimSpace(l) {
		case generator.MetaBegin:
			if start < 0 {
				start = i
			}
		case generator.MetaEnd:
			if start >= 0 && end < 0 {
				end = i
			}
		}
	}
	if start < 0 || end < 0 {
		return "", ErrNoMarker
	}

	var out strings.Builder
	for _, l := range lines[start+1 : end] {
		switch {
		case strings.HasPrefix(l, "# "):
			out.WriteString(l[2:])
		case l == "#":
		default:
			return "", fmt.Errorf("line inside the meta block is not a comment: %q", l)
		}
		out.WriteByte('\n')
	}
	return out.String(), nil
}
